<!DOCTYPE html>

<html><head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <script src="lib/three.min.js"></script>
  <script src="lib/orbitcontrols.js"></script>
  <!-- fallback if no WebGL -->
  <script src="lib/projector.js"></script>
  <script src="lib/canvasrenderer.js"></script>
  <script src="lib/jquery-2.1.3.min.js"></script>
  <script src="src/csg.js"></script>
  <script src="src/threecsg.js"></script>
  <script src="src/openjscad.js"></script>
  <script src="src/formats.js"></script>
  <style>

body {
  font: 14px/20px 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif;
  max-width: 820px;
  margin: 0 auto;
  padding: 10px;
}

pre, code, textarea {
  font: 12px/20px Monaco, monospace;
  border: 1px solid #CCC;
  border-radius: 3px;
  background: #F9F9F9;
  padding: 0 3px;
  color: #555;
}
pre, textarea {
  padding: 10px;
  width: 100%;
}
textarea {
  height: 200px;
}
textarea:focus {
  outline: none;
}

canvas { cursor: move; }

  </style>
<link rel="stylesheet" href="openjscad.css" type="text/css">

<script>

var gProcessor=null;

// Show all exceptions to the user:
OpenJsCad.AlertUserOfUncaughtExceptions();

function onload()
{
    document.addEventListener("paramsUpdatedEvent", function(e){
        //console.debug("Caught event!:",e.detail);
        gProcessor.rebuildSolid();
        }, false);
  gProcessor = new OpenJsCad.Processor(document.getElementById("viewer"));
  updateSolid();
}

function updateSolid()
{
gProcessor.setJsCad(document.getElementById('code').value);
}
function getExample(name) {
  var el = document.getElementById('code');
  $.get('examples/' + name, function(data) {
    el.value = data;
    updateSolid();
  });
}

function update_parameter(name, value)
{
    let param = document.getElementById("param."+name);
    param.value = value;
}

function loadExample(exampleNo)
{

    switch(exampleNo)
    {
        case "1":

            update_parameter("cup_inner_diameter", 60.0);
            update_parameter("cup_top_height", 30.0);
            update_parameter("cup_bottom_height", 30.0);
            update_parameter("indent_outer_diameter", 30.0);
            update_parameter("indent_inner_diameter", 10.0);
            update_parameter("cup_top_squareness", 22.0);
            update_parameter("cup_top_indent", 2.0);
            update_parameter("material_thickness", 1.0);
            update_parameter("number_of_rings", 3);
            update_parameter("ring_spacing", 6.0);
            update_parameter("ring_style", "ROOT");
            update_parameter("ring_width", 3.0);
            update_parameter("ring_height", 6.0);
            update_parameter("ring_squareness", 2.0);
            update_parameter("color", "SG");
            update_parameter("top_style", "S");
        break;
        case "2":

            update_parameter("cup_inner_diameter", 60.0);
            update_parameter("cup_top_height", 60.0);
            update_parameter("cup_bottom_height", 25.0);
            update_parameter("indent_outer_diameter", 35.0);
            update_parameter("indent_inner_diameter", 10.0);
            update_parameter("cup_top_squareness", 0.0);
            update_parameter("cup_top_indent", 2.0);
            update_parameter("material_thickness", 1.0);
            update_parameter("number_of_rings", 1.0);
            update_parameter("ring_spacing", 0.0);
            update_parameter("ring_style", "POLY");
            update_parameter("ring_width", 2.0);
            update_parameter("ring_height", 27.0);
            update_parameter("ring_squareness", 10.0);
            update_parameter("color", "S");
            update_parameter("top_style", "S");
        break;
        case "3":
            update_parameter("cup_inner_diameter", 63.7);
            update_parameter("cup_top_height", 35.33);
            update_parameter("cup_bottom_height", 36.1);
            update_parameter("indent_outer_diameter", 37.77);
            update_parameter("indent_inner_diameter", 10.28);
            update_parameter("cup_top_squareness", 20.0);
            update_parameter("cup_top_indent", 2.5);
            update_parameter("material_thickness", 1.0);
            update_parameter("number_of_rings", 2.0);
            update_parameter("ring_spacing", 6.0);
            update_parameter("ring_style", "SIN");
            update_parameter("ring_width", 3.0);
            update_parameter("ring_height", 6.72);
            update_parameter("ring_squareness", 2);
            update_parameter("color", "C");
            update_parameter("top_style", "S");
        break;
    }
    gProcessor.rebuildSolid();
}



</script>
<title>Parametric Cup Generator</title>  
</head>
<body onload="onload()">
<span>
    <h1>Parametric Cup Generator</h1>
    <h5>For the Cups and Balls Routine by Brandon Gruber - Last Updated 9/16/2021</h5>
</span>
<button type="button" onclick="loadExample('1')">Foxian Cup</button><button type="button" onclick="loadExample('2')">Medieval Cup</button><button type="button" onclick="loadExample('3')">Regular</button>
<div id="viewer"></div>
<h2>Playground</h2>
You can also directly edit the javascript below for this model. Beware that all changes will be lost when you navigate away from the page.
<br><br>

<textarea id="code">

function main(params)
{
    if( undefined === params.number_of_rings )
        params.number_of_rings = 0;

    //precalc some radiai
    params.cup_inner_radius = params.cup_inner_diameter/2;
    params.cup_outer_radius = params.cup_inner_radius + params.material_thickness;
    params.cup_indent_outer_radius = params.indent_outer_diameter/2;
    params.cup_indent_inner_radius = params.indent_inner_diameter/2;

    //Determine the preview colors.
    switch(params.color)
    {
        case "C"://copper
            params.cup_color = [0.90, 0.50, 0.24];
            params.ring_color = params.cup_color;
        break;
        case "S"://silver
            params.cup_color = [192/255, 192/255, 192/255];
            params.ring_color = params.cup_color;
        break;
        case "G"://gold
            params.cup_color = [1, 215/255, 0];
            params.ring_color = params.cup_color;
        break;
        case "SG"://silver cup and gold rings
            params.cup_color = [192/255, 192/255, 192/255];
            params.ring_color = [1, 215/255, 0];
        break;
    }

    //Determine the resolution of the result
    switch(params.render_quality)
    {
        default:
            params.curve_generation_resolution = 1;
            params.rotate_extrude_resolution = 32;
        break;
        case "OK":
            params.curve_generation_resolution = 0.5;
            params.rotate_extrude_resolution = 64;
        break;
        case "BEST":
            params.curve_generation_resolution = 0.1;
            params.rotate_extrude_resolution = 128;
        break;

    }

    //create the body of the cup
    let result = (params.top_style == 'S') ? cup_rounded_square(params) : cup_rounded(params);

    if( 0 == params.number_of_rings )
        return result;

    let body = null;
    for( thing in result )
    {
        console.debug(result[thing].name);
        if(result[thing].name == 'cup')
        {
            body = result[thing].data;
        }
    }

    //rings are handled separately because there may not be any if you set number_of_rings to 0, and they may be a different color that the body.

    let rings = cup_rings(params);
    let single_ring_at_origin_dict = {
        name: 'ring',
        caption: 'Ring Only',
        data: ring(params.ring_height, params),
    }
    result.splice(0, 0, single_ring_at_origin_dict);
    let body_with_rings_dict = {
        name:'body_with_rings',
        caption: 'Cup with Rings Attached',
        data: body.union(rings),
    };
    result.splice(0, 0, body_with_rings_dict);

    return result;


}

function ring(z=100, params)
{
    var points = [];
    let width = params.ring_height;//ring_height is the width of the curve
    let height = params.ring_width;//ring_width is the hight of the curve
    for(var x = 0; x <= width; x += params.curve_generation_resolution)
    {
            let y = 0;
            switch(params.ring_style)
            {
              case "ROOT":
                //Rounded
                y = (height/Math.sqrt(width/4))*Math.sqrt(x - (Math.pow(x,2)/width));
              break;
              case "POLY":
                //Rounded-square
                y = height*(1-Math.pow(
                    (2*x-width)/width,
                    2+(2*params.ring_squareness)
                ));

              break;
              default:
                //Can be more triangularly rounded (sin wave)
                y = height*Math.sin((Math.PI*x)/width);
            }
            if (Number.isNaN(y))
              y = 0;
            points.push(new CSG.Vector2D(y, x));
    }

    let result = new CSG.Polygon2D(points);
    //return result.extrude({"offset":[0,0,1]});//test line to just inspect the polygon shape
    result = result.translate([params.cup_outer_radius, 0, 0]).rotateExtrude({"resolution":params.rotate_extrude_resolution});
    result = result.translate([0, 0, z]);//move to the correct Z location,
    return result.setColor(params.ring_color);//set color
}

function cup_rings(params)
{
    let rings = [];
    for(let i = 0; i < params.number_of_rings; ++i)
    {
        let r;
        if((i%2) == 0)
        {
            r  = ring((i/2)*(params.ring_spacing+params.ring_height), params);
        }
        else{
            r = ring((params.cup_bottom_height-params.ring_height)-(((i-1)/2)*(params.ring_spacing+params.ring_height)), params);
        }
        rings.push(r);
    }
    return rings;
}


/*****************************************
* Generates the curve for the top.
* @param x is f(x)
* @param w is the radius of cup
* @param h is the hight of the top of the cup
* @param sq is the coeficient of the curve making the curve more square or less wide. A 0 ends up being a straight line.
******************************************/
function top_shape_polynomial(x, w, h, sq)
{
    return h-h*Math.pow(x/w,(1*(1+sq/10)));
}


function find_inside_radius_x_at_y(points, y, invert_xy=false)
{

    let x_index = invert_xy ? 1 : 0;
    let y_index = invert_xy ? 0 : 1;

    let closest_point = points[0];

    for( let i = 1; i < points.length; ++i )
    {
        let p = points[i];

        let p_y = p[y_index];
        let c_y = closest_point[y_index];

        let current_delta = Math.abs(c_y - y);
        let loop_delta = Math.abs(p_y - y);
        if (loop_delta < current_delta)
        {
            closest_point = p;
        }
    }
    //console.log("The closest x: " + closest_point[x_index] + " for y: " + y + " in point:" + closest_point);
    return closest_point[x_index];
}


function chop_cup_magnet_cover(params, inside_points)
{

    let magnet_height = 0.1 + params.magnet_height;
    let indent_total_radius = params.cup_indent_outer_radius + params.cup_indent_inner_radius;
    let indent_hypot = Math.hypot(params.cup_top_indent, params.cup_indent_outer_radius - params.cup_indent_inner_radius);
    let indent_angle_A = Math.atan(params.cup_top_indent/ (params.cup_indent_outer_radius - params.cup_indent_inner_radius));
    let indent_angle_B = Math.PI/2 - indent_angle_A;
    let indent_x = indent_hypot * Math.sin(indent_angle_B);
    let indent_y = indent_hypot * Math.cos(indent_angle_B);

    let indent_angle_sin = Math.sin(indent_angle_B) * params.material_thickness;
    let indent_angle_cos = Math.cos(indent_angle_B) * params.material_thickness;
    let crossection_width = params.material_thickness/(Math.cos(indent_angle_B)*Math.tan(indent_angle_B));

    console.debug("angle A:", 180*indent_angle_A/Math.PI, "angle B:", 180*indent_angle_B/Math.PI);
    console.debug("indent_total_radius: ", indent_total_radius);
    console.debug("indent_hypot: ", indent_hypot);
    console.debug("indent_angle_A: ", indent_angle_A);
    console.debug("indent_angle_B: ", indent_angle_B );
    console.debug("indent_x: ", indent_x);
    console.debug("indent_y: ", indent_y);
    console.debug("indent_angle_sin: ", indent_angle_sin);
    console.debug("indent_angle_cos: ", indent_angle_cos);
    console.debug("crossection_width: ", crossection_width);

    let points = [];


    let first_post_outer_edge_x = params.cup_indent_outer_radius + params.material_thickness;
    let first_post_outer_base_y_above_material = params.cup_top_height - magnet_height;
    let first_post_outer_base_y_below_material = first_post_outer_base_y_above_material - params.material_thickness*Math.cos(indent_angle_A);

    //first post bottom inside point
    points.push([params.cup_indent_outer_radius,
            params.cup_top_height - magnet_height]);

    //first post top iniside point
    points.push([params.cup_indent_outer_radius,
            params.cup_top_height - params.material_thickness]);

    //top of the first post outer edge
    points.push([
        first_post_outer_edge_x,
        params.cup_top_height - params.material_thickness
    ]);

    //first post on the left bottom
    points.push([
            first_post_outer_edge_x,
            first_post_outer_base_y_above_material
    ]);

    let inside_radius_at_y = find_inside_radius_x_at_y(inside_points, first_post_outer_base_y_above_material);

    if(inside_radius_at_y > params.cup_inner_radius){
        console.log("Error too large: " + inside_radius_at_y);
        inside_radius_at_y = params.cup_inner_radius;
    }

    if(inside_radius_at_y < (params.cup_indent_outer_radius + params.material_thickness)){
        console.log("Error too small:" + inside_radius_at_y);
        inside_radius_at_y = (params.cup_indent_outer_radius + params.material_thickness);
    }


    //point at the edge of the cup above material
    points.push([
            inside_radius_at_y,
            first_post_outer_base_y_above_material
    ]);

    inside_radius_at_y = find_inside_radius_x_at_y(inside_points, first_post_outer_base_y_below_material);

    if(inside_radius_at_y > params.cup_inner_radius){
        console.log("Error too large: " + inside_radius_at_y);
        inside_radius_at_y = params.cup_inner_radius;
    }

    if(inside_radius_at_y < (params.cup_indent_outer_radius + params.material_thickness)){
        console.log("Error too small:" + inside_radius_at_y);
        inside_radius_at_y = (params.cup_indent_outer_radius + params.material_thickness);
    }
    //point at the edge of the cup below material
    points.push([
            inside_radius_at_y,
            first_post_outer_base_y_below_material
    ]);



    //point at the edge of the first post if the edge cup point didn't exist
    points.push([
            params.cup_indent_outer_radius + params.material_thickness,
            first_post_outer_base_y_below_material
    ]);




    //second post left bottom
    points.push([
                    params.cup_indent_inner_radius+params.material_thickness + params.material_thickness*Math.sin(indent_angle_A),
                    params.cup_top_height - params.cup_top_indent - magnet_height - params.material_thickness
                ]);
    points.push([
                    0,
                    params.cup_top_height - params.cup_top_indent - magnet_height - params.material_thickness
                ]);
    points.push([
                    0,
                    params.cup_top_height - params.cup_top_indent - magnet_height
                ]);
    points.push([
                    params.cup_indent_inner_radius,
                    params.cup_top_height - params.cup_top_indent - magnet_height
                ]);
    points.push([
                    params.cup_indent_inner_radius,
                    params.cup_top_height - params.cup_top_indent - params.material_thickness
                ]);
    points.push([
                    params.cup_indent_inner_radius + params.material_thickness,
                    params.cup_top_height - params.cup_top_indent - params.material_thickness + params.material_thickness*Math.tan(indent_angle_A)
                ]);
    points.push([
                    params.cup_indent_inner_radius + params.material_thickness,
                    params.cup_top_height - params.cup_top_indent - magnet_height
                ]);

    points = new CSG.Path2D(points);
    points = points.close();
    let cover = points.innerToCAG();

    //test extrude
    //return cover.extrude([0,0,20]).setColor([0, 0, 1]).rotateX(90).rotateZ(-45);

    cover = cover.rotateExtrude({"resolution":params.rotate_extrude_resolution});
    cover = cover.translate([0, 0, params.cup_bottom_height]);//move to the correct Z location
    return cover.setColor(params.cup_color);//set color

}

function cup_rounded_square(params)
{

    let w_inner = (params.cup_inner_radius)-params.cup_indent_outer_radius;
    let w_outer = w_inner+params.material_thickness;
    let inside_points = [];
    let indent_radius = (params.indent_inner_diameter < params.indent_outer_diameter) ? params.cup_indent_inner_radius : params.cup_indent_outer_radius;

    /*create outer points of the cup*/
    let points = [];
    points.push( new CSG.Vector2D(0, params.cup_top_height-params.cup_top_indent) );
    points.push( new CSG.Vector2D(indent_radius, params.cup_top_height-params.cup_top_indent ) );
    for(let x = 0;x <= w_outer; x += params.curve_generation_resolution){
        let y = top_shape_polynomial(x, w_outer, params.cup_top_height, params.cup_top_squareness);

        points.push( new CSG.Vector2D(x+params.cup_indent_outer_radius, y ));
    }

    /* bottom two make the bottom of the cup */
    points.push( new CSG.Vector2D(params.cup_outer_radius, 0) );
    points.push( new CSG.Vector2D(params.cup_outer_radius, params.cup_bottom_height*-1) );
    points.push( new CSG.Vector2D(params.cup_inner_radius, params.cup_bottom_height*-1) );
    points.push( new CSG.Vector2D(params.cup_inner_radius, 0) );

    /*create inner points of the cup*/
    for(let x = w_inner; x >= 0; x -= params.curve_generation_resolution){
        let y = top_shape_polynomial(x, w_inner, params.cup_top_height-params.material_thickness, params.cup_top_squareness);
        points.push( new CSG.Vector2D(x+params.cup_indent_outer_radius, y ));
        inside_points.push([x+params.cup_indent_outer_radius, y]);
    }
    points.push( new CSG.Vector2D(indent_radius, params.cup_top_height-params.cup_top_indent-params.material_thickness ) );
    points.push( new CSG.Vector2D(0, params.cup_top_height-params.cup_top_indent-params.material_thickness) );

    let top = new CSG.Polygon2D(points);

    // To test the shape uncomment
    //top = top.extrude([0,0,1]).setColor([1, 0, 0]).rotateX(90).rotateZ(-45);
    //return top.union(chop_cup_magnet_cover(params, inside_points));

    /* rotate extrude spins the shape around the Z axis*/
    let shell = top.rotateExtrude({"resolution":params.rotate_extrude_resolution});
    shell = shell.translate([0, 0, params.cup_bottom_height]);//move to the correct Z location
    shell = shell.setColor(params.cup_color)




    if(params.magnet_height)
    {
        let chop_cup_cover = chop_cup_magnet_cover(params, inside_points);
         return [
            {
                name: "cup",
                caption: "Cup Body",
                data: shell,
            },
            {
                name: "magnet cover",
                caption: "Chop-Cup Magnet Cover",
                data: chop_cup_cover,
            }
        ];
    }
    else
    {
         return [
            {
                name: "cup",
                caption: "Cup Body",
                data: shell,
            }
        ];
    }


}

// Here we define the user editable parameters: 
function getParameterDefinitions()
{

    let param_rounded_modifier_x_values = [];
    let param_rounded_modifier_x_captions = [];
    let param_rounded_modifier_y_values = [];
    let param_rounded_modifier_y_captions = [];

    /*since there is no support for range yet. I'll make this a drop down for now.*/
    for(let i = 1; i <= 100; ++i)
    {
        let full =  "==============================";
        let ammount = i * full.length / 100;
        let bar = full.slice(0, ammount) + i;

        param_rounded_modifier_x_values.push(i);
        param_rounded_modifier_x_captions.push(bar);
        param_rounded_modifier_y_values.push(i);
        param_rounded_modifier_y_captions.push(bar);
    }

  let params = [
    {
      name: 'render_quality',
      type: 'choice',
      values: ["PREVIEW", "OK", "BEST"],
      captions: ["Preview/Faster", "Medium", "High/Best/(May take minutes to render)"],
      caption: 'Render Quality:',
      initial: "PREVIEW",
    },
    { name: 'cup_inner_diameter', caption: 'Inside Diameter (mm):', type: 'float', default: 60.0 },
    { name: 'material_thickness', caption: 'Thickness (mm)', type: 'float', default: 1.0},
    { name: 'cup_top_indent', caption: 'Top Indent Depth (mm):', type: 'float', default: 2.0 },
    { name: 'indent_outer_diameter', caption: 'Top Indent Outer Diameter (mm):', type: 'float', default: 30.0 },
    { name: 'indent_inner_diameter', caption: 'Top Indent Inner Diameter (mm):', type: 'float', default: 20.0 },
    { name: 'magnet_height', caption: 'Chop-Cup Magnet Height (mm)(0 = Disabled):', type: 'float', default: 0},
    { name: 'cup_top_height', caption: 'Top Height (mm):', type: 'float', default: 30.0 },
    {
      name: 'top_style',
      type: 'choice',
      values: ["S", "R"],
      captions: ["Rounded-Square", "Rounded"],
      caption: 'Top Curve Style:',
      initial: "S",
    },
    { name: 'cup_top_squareness', caption: 'Top Style Rounded-Square Squareness (unitless coefficient):', type: 'int', default: 22.0},
    {
      name: 'rounded_top_x',
      type: 'choice',
      values: param_rounded_modifier_x_values,
      captions: param_rounded_modifier_x_captions,
      caption: 'Top Style Rounded Outward-Bend Ammount (Percentage):',
      initial: 89,
    },
    {
      name: 'rounded_top_y',
      type: 'choice',
      values: param_rounded_modifier_y_values,
      captions: param_rounded_modifier_y_captions,
      caption: 'Top Style Rounded Upward-Bend Ammount (Percentage):',
      initial: 70,
    },
    { name: 'cup_bottom_height', caption: 'Bottom Height (mm):', type: 'float', default: 30.0},
    { name: 'number_of_rings', caption: 'Number Of Rings', type: 'int', default: 3},
    { name: 'ring_spacing', caption: 'Ring Spacing (mm)', type: 'float', default: 6.0},
    {
      name: 'ring_style',
      type: 'choice',
      values: ["ROOT", "POLY", "SIN"],
      captions: ["Rounded", "Rounded-Square", "Steep-Rounded"],
      caption: 'Ring Curve Style:',
      initial: "ROOT",
    },
    { name: 'ring_width', caption: 'Ring Width (mm):', type: 'float', default: 3.0},
    { name: 'ring_height', caption: 'Ring Height (mm):', type: 'float', default: 6.0},
    { name: 'ring_squareness', caption: 'Ring Squareness (unitless coefficient):', type: 'float', default: 2.0},
    {
      name: 'color',
      type: 'choice',
      values: ["C", "S", "G", "SG"],
      captions: ["Copper", "Silver", "Gold", "Silver & Gold"],
      caption: 'Preview Color:',
      initial: "SG",
    },
  ];


    return params;
}

    function cup_rounded(params)
{
    var bend_point_ratio_x = params.rounded_top_x/100;
    var bend_point_ratio_y = params.rounded_top_y/100;



    var outer_path=new CSG.Path2D([
        [0, -1*params.cup_bottom_height],//forms the bottom of the cup
        [params.cup_outer_radius, -1*params.cup_bottom_height],
        [params.cup_outer_radius,0]//point where the bottom of the cup and the top meet
    ]);


    outer_path = outer_path.appendBezier(
        [[params.indent_outer_diameter*bend_point_ratio_x, params.cup_top_height*bend_point_ratio_y],
        [(params.cup_indent_outer_radius) + params.material_thickness, params.cup_top_height]], {resolution: params.rotate_extrude_resolution});

    outer_path = outer_path.appendPoints(
        [
            [(params.cup_indent_outer_radius), params.cup_top_height],//Additional point without the material thickness added to allow for steep indent angles
            [params.cup_indent_inner_radius + params.material_thickness, params.cup_top_height - params.cup_top_indent],
            [0, params.cup_top_height - params.cup_top_indent],
            [0,0]
        ]

    );

    // close the path and convert to a solid 2D shape:
    outer_path = outer_path.close();
    let outer_shape = outer_path.innerToCAG();


    let inner_path=new CSG.Path2D([
        [0, -1*params.cup_bottom_height -1],//forms the bottom of the cup
        [params.cup_inner_radius, -1*params.cup_bottom_height],
        [params.cup_inner_radius,0]
    ]);

    inner_path = inner_path.appendBezier(
        [[(params.indent_outer_diameter)*bend_point_ratio_x, (params.cup_top_height-params.material_thickness)*bend_point_ratio_y],
        [(params.cup_indent_outer_radius)+params.material_thickness, params.cup_top_height-params.material_thickness]], {resolution: params.rotate_extrude_resolution});

    inner_path = inner_path.appendPoints(
        [
            [(params.cup_indent_inner_radius) + (2*params.material_thickness), params.cup_top_height - params.cup_top_indent - params.material_thickness],//2x material thickness on the X is for allowing for steep indents
            [0, params.cup_top_height - params.cup_top_indent - params.material_thickness],
            [0,0]
        ]

    );

    // close the path and convert to a solid 2D shape:
    inner_path = inner_path.close();
    let inner_shape = inner_path.innerToCAG();
    let shell = outer_shape.subtract(inner_shape);

    //shell = shell.extrude({"offset":[0,0,0.5]}).rotateX(90).rotateZ(-45);//test line to just inspect the polygon shape

    shell = shell.rotateExtrude({"resolution":params.rotate_extrude_resolution});
    shell = shell.translate([0, 0, params.cup_bottom_height]);//move to the correct Z location,
    shell = shell.setColor(params.cup_color);

    if(params.magnet_height)
    {
        let inner_points_for_chop_cup_gen = [];
        for( point in inner_path.points )
        {
            let p = inner_path.points[point];
            let p2 = [p._x, p._y];
            inner_points_for_chop_cup_gen.push(p2);
        }
        let chop_cup_cover = chop_cup_magnet_cover(params, inner_points_for_chop_cup_gen);
        return [
            {
                name: "cup",
                caption: "Cup Body",
                data: shell,
            },
            {
                name: "magnet cover",
                caption: "Chop-Cup Magnet Cover",
                data: chop_cup_cover,
            }
        ];
    }
    else
    {
        return [
            {
                name: "cup",
                caption: "Cup Body",
                data: shell,
            }
        ];
    }


}


</textarea><br>
<input type="submit" value="Update" onclick="updateSolid(); return false;">
<br>

<h2>About This Page</h2>
This is a page forked from the <a href="https://joostn.github.io/OpenJsCad/">OpenJsCAD</a> page to generate a custom cup for the cups and balls routine. Tweak the parameters as desired, then download the model with "Generate STL button".

<h2>Release Notes</h2>
<ul>
    <li>
        Currently, the "Rounded" Cup-Top style is experimental as it doesn't work well with the way I am generating the chop-cup magnet cover, and the cup generated could be too thin depending on the shape, but it should be a better looking shape in the end.
    </li>
    <li>
        I need to have some logic when generating the cup such that it's gaurenteed to nest well, and not be loose. Currently, this is up to you to test manually.
    </li>
    <li>
        When you generate an STL file, it may have errors when loaded into a slicer, but I believe that you could repair the errors with Meshmixer or some other utility, but it may not even be necessary. Try slicing it first to see.
    </li>
</ul>




<h2>Viewer navigation</h2>
Click and drag to rotate the model around the origin. Hold down Alt to change the axis of rotation.
Shift+Drag moves the model around. Zoom using the mouse wheel or using the slider below the model.

<h2>About OpenJsCAD</h2>
<a href="https://joostn.github.io/OpenJsCad/">OpenJsCAD</a> is a 2D and 3D modeling tool similar to <a href="http://www.openscad.org/">OpenSCAD</a>,
but web based and using Javascript language.


<h2>Original OpenJsCAD License</h2>
OpenJsCad is developed by <a href="https://github.com/joostn">Joost Nieuwenhuijse</a>.
Based on <a href="https://github.com/evanw/csg.js">initial CSG.js</a> copyright (c) 2011 <a href="https://github.com/evanw">Evan Wallace</a>.
Uses <a href="https://github.com/evanw/lightgl.js">lightgl.js</a> by <a href="https://github.com/evanw">Evan Wallace</a> 
and <a href="https://github.com/toaarnio">Tomi Aarnio</a> for WebGL rendering. 
Contributions by <a href="https://github.com/alx">Alexandre Girard</a>, 
 <a href="https://github.com/tlrobinson">Tom Robinson</a>,
 <a href="https://github.com/jboecker">jboecker</a>,
 <a href="https://github.com/risacher">risacher</a>,
 <a href="https://github.com/tedbeer">tedbeer</a>,
 <a href="https://github.com/bebbi">bebbi</a>,
 <a href="https://github.com/sahilshekhawat">Sahil Shekhawat</a>.
All code released under MIT license.

</body>
</html>
