<!DOCTYPE html>

<html><head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <script src="lib/three.min.js"></script>
  <script src="lib/orbitcontrols.js"></script>
  <!-- fallback if no WebGL -->
  <script src="lib/projector.js"></script>
  <script src="lib/canvasrenderer.js"></script>
  <script src="lib/jquery-2.1.3.min.js"></script>
  <script src="src/csg.js"></script>
  <script src="src/threecsg.js"></script>
  <script src="src/openjscad.js"></script>
  <script src="src/formats.js"></script>
  <style>

body {
  font: 14px/20px 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif;
  max-width: 820px;
  margin: 0 auto;
  padding: 10px;
}

pre, code, textarea {
  font: 12px/20px Monaco, monospace;
  border: 1px solid #CCC;
  border-radius: 3px;
  background: #F9F9F9;
  padding: 0 3px;
  color: #555;
}
pre, textarea {
  padding: 10px;
  width: 100%;
}
textarea {
  height: 200px;
}
textarea:focus {
  outline: none;
}

canvas { cursor: move; }

  </style>
<link rel="stylesheet" href="openjscad.css" type="text/css">

<script>

var gProcessor=null;

// Show all exceptions to the user:
OpenJsCad.AlertUserOfUncaughtExceptions();

function onload()
{
    document.addEventListener("paramsUpdatedEvent", function(e){
        //console.debug("Caught event!:",e.detail);
        gProcessor.rebuildSolid();
        }, false);
  gProcessor = new OpenJsCad.Processor(document.getElementById("viewer"));
  updateSolid();
}

function updateSolid()
{
gProcessor.setJsCad(document.getElementById('code').value);
}
function getExample(name) {
  var el = document.getElementById('code');
  $.get('examples/' + name, function(data) {
    el.value = data;
    updateSolid();
  });
}

function update_parameter(name, value)
{
    let param = document.getElementById("param."+name);
    param.value = value;
}

function loadExample(exampleNo)
{

    switch(exampleNo)
    {
        case "1":

            update_parameter("cup_inner_diameter", 60);
            update_parameter("cup_top_height", 30);
            update_parameter("cup_bottom_height", 30);
            update_parameter("cup_top_outer_diameter", 30);
            update_parameter("cup_top_inner_diameter", 10);
            update_parameter("cup_top_squareness", 22);
            update_parameter("cup_top_indent", 2);
            update_parameter("material_thickness", 1);
            update_parameter("number_of_rings", 3);
            update_parameter("ring_spacing", 6);
            update_parameter("ring_style", "ROOT");
            update_parameter("ring_width", 3);
            update_parameter("ring_height", 6);
            update_parameter("ring_squareness", 2);
            update_parameter("color", "SG");

        break;
        case "2":

            update_parameter("cup_inner_diameter", 60);
            update_parameter("cup_top_height", 60);
            update_parameter("cup_bottom_height", 25);
            update_parameter("cup_top_outer_diameter", 35);
            update_parameter("cup_top_inner_diameter", 10);
            update_parameter("cup_top_squareness", 0);
            update_parameter("cup_top_indent", 2);
            update_parameter("material_thickness", 1);
            update_parameter("number_of_rings", 1);
            update_parameter("ring_spacing", 0);
            update_parameter("ring_style", "POLY");
            update_parameter("ring_width", 2);
            update_parameter("ring_height", 27);
            update_parameter("ring_squareness", 10);
            update_parameter("color", "S");

        break;
        case "3":
            update_parameter("cup_inner_diameter", 60);
            update_parameter("cup_top_height", 50);
            update_parameter("cup_bottom_height", 30);
            update_parameter("cup_top_outer_diameter", 30);
            update_parameter("cup_top_inner_diameter", 20);
            update_parameter("cup_top_squareness", 20);
            update_parameter("cup_top_indent", 2);
            update_parameter("material_thickness", 1);
            update_parameter("number_of_rings", 2);
            update_parameter("ring_spacing", 6);
            update_parameter("ring_style", "SIN");
            update_parameter("ring_width", 3);
            update_parameter("ring_height", 7);
            update_parameter("ring_squareness", 2);
            update_parameter("color", "C");
        break;
    }
    gProcessor.rebuildSolid();
}

</script>
<title>Parametric Cup Generator</title>  
</head>
<body onload="onload()">
<h1>Parametric Cup Generator</h1>
<h5>For the Cups and Balls Routine by Brandon Gruber - Last Updated 8/24/2021</h5>
<button type="button" onclick="loadExample('1')">Foxian Cup</button><button type="button" onclick="loadExample('2')">Medieval Cup</button><button type="button" onclick="loadExample('3')">Regular</button>
<div id="viewer"></div>
<h2>Playground</h2>
You can also directly edit the javascript below for this model. Beware that all changes will be lost when you navigate away from the page.
<br><br>

<textarea id="code">

function main(params)
{
    if( undefined === params.number_of_rings )
        params.number_of_rings = 0;

    //Determine the preview colors.
    switch(params.color)
    {
        case "C"://copper
            params.cup_color = [0.90, 0.50, 0.24];
            params.ring_color = params.cup_color;
        break;
        case "S"://silver
            params.cup_color = [192/255, 192/255, 192/255];
            params.ring_color = params.cup_color;
        break;
        case "G"://gold
            params.cup_color = [1, 215/255, 0];
            params.ring_color = params.cup_color;
        break;
        case "SG"://silver cup and gold rings
            params.cup_color = [192/255, 192/255, 192/255];
            params.ring_color = [1, 215/255, 0];
        break;
    }

    //Determine the resolution of the result
    switch(params.render_quality)
    {
        default:
            params.curve_generation_resolution = 1;
            params.rotate_extrude_resolution = 32;
        break;
        case "OK":
            params.curve_generation_resolution = 0.5;
            params.rotate_extrude_resolution = 64;
        break;
        case "BEST":
            params.curve_generation_resolution = 0.1;
            params.rotate_extrude_resolution = 128;
        break;

    }

    //create the body of the cup
    let body = cup_body(params);

    //rings are handled separately because there may not be any if you set number_of_rings to 0, and they may be a different color that the body.
    if(params.number_of_rings){
        //rings + body + top
        let rings = cup_rings(params);//returns an array of dictionaries that we can just add the body to
        return body.union(rings);
    }
    else
    {
        //only body + top. Dont know why you would want that but there you go.
        return cup;
    }

}

function ring(z=100, params)
{
    let cup_radius = params.cup_inner_diameter/2 + params.material_thickness;
    var points = [];
    let width = params.ring_height;//ring_height is the width of the curve
    let height = params.ring_width;//ring_width is the hight of the curve
    for(var x = 0; x <= width; x += params.curve_generation_resolution)
    {
            let y = 0;
            switch(params.ring_style)
            {
              case "ROOT":
                //Rounded
                y = (height/Math.sqrt(width/4))*Math.sqrt(x - (Math.pow(x,2)/width));
              break;
              case "POLY":
                //Rounded-square
                y = height*(1-Math.pow(
                    (2*x-width)/width,
                    2+(2*params.ring_squareness)
                ));

              break;
              default:
                //Can be more triangularly rounded (sin wave)
                y = height*Math.sin((Math.PI*x)/width);
            }
            if (Number.isNaN(y))
              y = 0;
            points.push(new CSG.Vector2D(y, x));
    }

    let result = new CSG.Polygon2D(points);
    //return result.extrude({"offset":[0,0,1]});//test line to just inspect the polygon shape
    result = result.translate([cup_radius, 0, 0]).rotateExtrude({"resolution":params.rotate_extrude_resolution});
    result = result.translate([0, 0, z]);//move to the correct Z location,
    return result.setColor(params.ring_color);//set color
}

function cup_rings(params)
{
    let rings = [];
    for(let i = 0; i < params.number_of_rings; ++i)
    {
        let r;
        if((i%2) == 0)
        {
            r  = ring((i/2)*(params.ring_spacing+params.ring_height), params);
        }
        else{
            r = ring((params.cup_bottom_height-params.ring_height)-(((i-1)/2)*(params.ring_spacing+params.ring_height)), params);
        }
        rings.push(r);
    }
    return rings;
}


/*****************************************
* Generates the curve for the top.
* @param x is f(x)
* @param w is the radius of cup
* @param h is the hight of the top of the cup
* @param sq is the coeficient of the curve making the curve more square or less wide. A 0 ends up being a straight line.
******************************************/
function top_shape_polynomial(x, w, h, sq)
{
    return h-h*Math.pow(x/w,(1*(1+sq/10)));
}


function cup_body(params)
{

    let br = params.cup_top_outer_diameter/2;
    let w_inner = (params.cup_inner_diameter/2)-br;
    let w_outer = w_inner+params.material_thickness;

    let indent_radius = (params.cup_top_inner_diameter < params.cup_top_outer_diameter) ? params.cup_top_inner_diameter/2 : params.cup_top_outer_diameter/2;

    /*create outer points of the cup*/
    let points = [];
    points.push( new CSG.Vector2D(0, params.cup_top_height-params.cup_top_indent) );
    points.push( new CSG.Vector2D(indent_radius, params.cup_top_height-params.cup_top_indent ) );
    for(let x = 0;x <= w_outer; x += params.curve_generation_resolution){
        let y = top_shape_polynomial(x, w_outer, params.cup_top_height, params.cup_top_squareness);

        points.push( new CSG.Vector2D(x+br, y ));
    }

    /* bottom two make the bottom of the cup */
    points.push( new CSG.Vector2D(params.cup_inner_diameter/2 + params.material_thickness, 0) );
    points.push( new CSG.Vector2D(params.cup_inner_diameter/2 + params.material_thickness, params.cup_bottom_height*-1) );
    points.push( new CSG.Vector2D(params.cup_inner_diameter/2, params.cup_bottom_height*-1) );
    points.push( new CSG.Vector2D(params.cup_inner_diameter/2, 0) );

    /*create inner points of the cup*/
    for(let x = w_inner; x >= 0; x -= params.curve_generation_resolution){
        let y = top_shape_polynomial(x, w_inner, params.cup_top_height-params.material_thickness, params.cup_top_squareness);
        points.push( new CSG.Vector2D(x+br, y ));
    }
    points.push( new CSG.Vector2D(indent_radius, params.cup_top_height-params.cup_top_indent-params.material_thickness ) );
    points.push( new CSG.Vector2D(0, params.cup_top_height-params.cup_top_indent-params.material_thickness) );

    let top = new CSG.Polygon2D(points);

    // To test the shape uncomment
    //top = top.extrude([0,0,1]).setColor([1, 0, 0]).rotateX(90);
    //return top.translate([0, 0, params.cup_bottom_height]);

    /* rotate extrude spins the shape around the Z axis */
    let shell = top.rotateExtrude({"resolution":params.rotate_extrude_resolution});
    shell = shell.translate([0, 0, params.cup_bottom_height]);//move to the correct Z location
    return shell.setColor(params.cup_color);//set color

}

// Here we define the user editable parameters: 
function getParameterDefinitions()
{
  return [
    {
      name: 'render_quality',
      type: 'choice',
      values: ["PREVIEW", "OK", "BEST"],
      captions: ["Preview/Faster", "Medium", "High/Best/(May take minutes to render)"],
      caption: 'Render Quality:',
      initial: "PREVIEW",
    },
    { name: 'cup_inner_diameter', caption: 'Inside Diameter:', type: 'int', default: 60 },
    { name: 'cup_top_height', caption: 'Top Height:', type: 'int', default: 30 },
    { name: 'cup_bottom_height', caption: 'Bottom Height:', type: 'int', default: 30},
    { name: 'cup_top_outer_diameter', caption: 'Top Indent Outer Diameter:', type: 'int', default: 30 },
    { name: 'cup_top_inner_diameter', caption: 'Top Indent Inner Diameter:', type: 'int', default: 10 },
    { name: 'cup_top_squareness', caption: 'Top Squareness:', type: 'int', default: 22},
    { name: 'cup_top_indent', caption: 'Top Indent Depth:', type: 'int', default: 2 },
    { name: 'material_thickness', caption: 'Thickness', type: 'int', default: 1},
    { name: 'number_of_rings', caption: 'Number Of Rings', type: 'int', default: 3},
    { name: 'ring_spacing', caption: 'Ring Spacing', type: 'int', default: 6},
    {
      name: 'ring_style',
      type: 'choice',
      values: ["ROOT", "POLY", "SIN"],
      captions: ["Rounded", "Rounded-Square", "Steep-Rounded"],
      caption: 'Ring Curve Style:',
      initial: "ROOT",
    },
    { name: 'ring_width', caption: 'Ring Width:', type: 'int', default: 3},
    { name: 'ring_height', caption: 'Ring Height:', type: 'int', default: 6},
    { name: 'ring_squareness', caption: 'Ring Squareness:', type: 'int', default: 2},
    {
      name: 'color',
      type: 'choice',
      values: ["C", "S", "G", "SG"],
      captions: ["Copper", "Silver", "Gold", "Silver & Gold"],
      caption: 'Preview Color:',
      initial: "SG",
    },
  ];
}

</textarea><br>
<input type="submit" value="Update" onclick="updateSolid(); return false;">
<br>

<h2>About This Page</h2>
This is a page forked from the <a href="https://joostn.github.io/OpenJsCad/">OpenJsCAD</a> page to generate a custom cup for the cups and balls routine. Tweak the parameters as desired, then download the model with "Generate STL button".

<h2>Viewer navigation</h2>
Click and drag to rotate the model around the origin. Hold down Alt to change the axis of rotation.
Shift+Drag moves the model around. Zoom using the mouse wheel or using the slider below the model.

<h2>About OpenJsCAD</h2>
<a href="https://joostn.github.io/OpenJsCad/">OpenJsCAD</a> is a 2D and 3D modeling tool similar to <a href="http://www.openscad.org/">OpenSCAD</a>,
but web based and using Javascript language.


<h2>Original OpenJsCAD License</h2>
OpenJsCad is developed by <a href="https://github.com/joostn">Joost Nieuwenhuijse</a>.
Based on <a href="https://github.com/evanw/csg.js">initial CSG.js</a> copyright (c) 2011 <a href="https://github.com/evanw">Evan Wallace</a>.
Uses <a href="https://github.com/evanw/lightgl.js">lightgl.js</a> by <a href="https://github.com/evanw">Evan Wallace</a> 
and <a href="https://github.com/toaarnio">Tomi Aarnio</a> for WebGL rendering. 
Contributions by <a href="https://github.com/alx">Alexandre Girard</a>, 
 <a href="https://github.com/tlrobinson">Tom Robinson</a>,
 <a href="https://github.com/jboecker">jboecker</a>,
 <a href="https://github.com/risacher">risacher</a>,
 <a href="https://github.com/tedbeer">tedbeer</a>,
 <a href="https://github.com/bebbi">bebbi</a>,
 <a href="https://github.com/sahilshekhawat">Sahil Shekhawat</a>.
All code released under MIT license.
<br><br>
Contributions are welcome! It's all written in Javascript, so if you know how to use it you
know how to modify it as well.
To contribute go to <a href="https://github.com/joostn/OpenJsCad/tree/gh-pages">OpenJsCad at GitHub (gh-pages tree)</a>,
<a href="http://help.github.com/fork-a-repo/">create your own fork</a> and 
<a href="http://help.github.com/send-pull-requests/">send me a pull request</a>. Note that the code is maintained 
in the gh-pages branch, not the master branch. This is so that it can be accessed directly via Github pages.


</body>
</html>
